<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');

$this->htmlElement('body')->appendAttribute('class', 'item-set resource browse');
?>

<?php echo $this->pageTitle($translate('Item sets'), 2); ?>

<?php echo $this->searchFilters(); ?>

<div class="browse-controls">
    <?php echo $this->pagination(); ?>
    <div class="advanced-search-wrapper">
        <?php echo $this->hyperlink($translate('Advanced search'), $this->url(null, ['action' => 'search'], true), ['class' => 'advanced-search']); ?>
    </div>
</div>
<?php $this->trigger('view.browse.before'); ?>
<ul class="resource-list item-sets">
<?php
$headingTerm = $this->siteSetting('browse_heading_property_term');
$bodyTerm = $this->siteSetting('browse_body_property_term');
foreach ($itemSets as $itemSet):
    $heading = $headingTerm ? $itemSet->value($headingTerm, ['default' => $translate('[Untitled]')]) : $itemSet->displayTitle();
    $body = $bodyTerm ? $itemSet->value($bodyTerm) : $itemSet->displayDescription();
?>
    <li class="item-set resource">
        <div class="item-set-thumb">
            <div class="image"><?php echo $itemSet->linkRaw($this->thumbnail($itemSet, 'large')); ?></div>
            <h4><?php echo $itemSet->link($heading); ?></h4>
        </div>
    </li>
<?php endforeach; ?>
</ul>
<?php $this->trigger('view.browse.after'); ?>
<?php echo $this->pagination(); ?>
