<div class="search-results-title"><?php echo $this->pageTitle(sprintf($this->translate('Search results for “%s”'), $query)); ?></div>
<div class="search-results">
    <h2><?php echo $this->translate('Pages'); ?></h2>
    <?php if ($pages): ?>
    <ul>
        <?php foreach ($pages as $page): ?>
        <li><?php echo $page->link($page->title()); ?></li>
        <?php endforeach; ?>
    </ul>
    <?php echo $this->hyperlink(
        sprintf($this->translate('View all results (%s total)'), $pagesTotal),
        $this->url(
            'site/page-browse',
            ['controller' => 'page', 'action' => 'browse'],
            ['query' => ['fulltext_search' => $query]],
            true
        )
    ); ?>
    <?php else: ?>
    <p><?php echo $this->translate('No pages found'); ?></p>
    <?php endif; ?>
</div>
<div class="search-results">
    <h2><?php echo $this->translate('Items'); ?></h2>
    <?php if ($items): ?>
    <ul>
        <?php foreach ($items as $item): ?>
        <li>
            <?php if ($date = $item->value('dcterms:date')): ?>
                <div class="date"><?php echo $date; ?></div>
            <?php endif; ?>
            <h4><?php echo $item->link($item->displayTitle()); ?></h4>
        </li>
        <?php endforeach; ?>
    </ul>
    <div class="search-view-all">
    <?php echo $this->hyperlink(
        sprintf($this->translate('View all results (%s total)'), $itemsTotal),
        $this->url(
            'site/resource',
            ['controller' => 'item', 'action' => 'browse'],
            ['query' => ['fulltext_search' => $query]],
            true
        )
    ); ?>
    </div>
    <?php else: ?>
    <p><?php echo $this->translate('No items found'); ?></p>
    <?php endif; ?>
</div>
