<?php
$escape = $this->plugin('escapeHtml');
$siteTitle = $site->title();
$this->htmlElement('html')->setAttribute('lang', $this->lang());
$this->headMeta()->setCharset('utf-8');
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1');
$this->headTitle($siteTitle)->setSeparator(' · ');
$this->headTitle()->append($this->setting('installation_title', 'Omeka S'));
$this->headLink()->prependStylesheet($this->assetUrl('css/style.css'));
$this->headLink()->prependStylesheet($this->assetUrl('css/iconfonts.css', 'Omeka'));
$this->headLink()->prependStylesheet('//fonts.googleapis.com/css?family=Open+Sans:400,400italic,600,600italic,700italic,700');
$this->headLink()->prependStylesheet('//use.typekit.net/fqf4tdx.css');
$this->headScript()->prependFile($this->assetUrl('js/brands.min.js'));
$this->headScript()->prependFile($this->assetUrl('js/fontawesome.min.js'));
$this->headScript()->prependFile($this->assetUrl('js/default.js'));
$this->headScript()->prependFile($this->assetUrl('js/global.js', 'Omeka'));
$this->headScript()->prependFile($this->assetUrl('vendor/jquery/jquery.min.js', 'Omeka'));
$this->jsTranslate();
$this->trigger('view.layout');
$userBar = $this->userBar();
?>
<?php echo $this->doctype(); ?>
<?php echo $this->htmlElement('html'); ?>
    <head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headLink(); ?>
        <?php echo $this->headStyle(); ?>
        <?php echo $this->headScript(); ?>

        <!-- Global site tag (gtag.js) - Google Analytics -->
        <script async src="https://www.googletagmanager.com/gtag/js?id=UA-45616698-3"></script>
        <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());
        
        gtag('config', 'UA-45616698-3');
        </script>
        
        <style>
            <?php if ($accentColor = $this->themeSetting('accent_color')): ?>
            a:link,
            a:visited {
                color: <?php echo $accentColor; ?>
            }
            
            a:active,
            a:hover {
                color: <?php echo $accentColor; ?>;
                opacity: .75;
            }
            <?php endif; ?>
        </style>
    </head>

    <?php echo $this->htmlElement('body'); ?>
        <?php echo $userBar; ?>
        <div class="site-switcher">
            <h6>Explore the Archives <i class="fa fa-caret-right"></i></h6>
            <ul class="header-social">
               <li><a href="https://www.instagram.com/covid19archive1/" title="Instagram" target="_blank"><span class="fab fa-instagram" title="Instagram"></span></a></li> 
               <li><a href="https://twitter.com/covid19archive1" title="Twitter"><span class="fab fa-twitter" title="Twitter" target="_blank"></span></a></li> 
               <li><a href="https://www.facebook.com/A-Journal-of-The-Plague-Year-An-Archive-of-Covid-19-105440631192458" title="Facebook" target="_blank"><span class="fab fa-facebook" title="Facebook"></span></a></li> 
            </ul>
        </div>
        <div class="site-switcher-list">
            <?php $allSites = $this->api()->search('sites', ['sort_by' => 'title'])->getContent(); ?>
            <?php foreach ($allSites as $allSite): ?>
                <?php echo $this->hyperlink($allSite->title(), $allSite->siteUrl(), ['class' => 'site-link']); ?>
            <?php endforeach; ?>
        </div>
        
        <?php if ($this->themeSetting('header_image')): ?>
            <header style="background-image: url('<?php echo $this->themeSettingAssetUrl('header_image'); ?>');">
        <?php else: ?> 
            <header>
        <?php endif; ?>
            <h1>
                <a href="<?php echo $site->url(); ?>" class="site-title">
                <?php if ($this->themeSetting('logo')): ?>
                    <!-- <img src="<?php echo $this->themeSettingAssetUrl('logo'); ?>" alt="<?php echo $escape($siteTitle); ?>" /> -->
                    <img class="logo" src="<?php echo $this->assetUrl('img/logo.png'); ?>" alt="Journal of the Plague Year" />
                <?php else: ?>
                    <?php //echo $escape($siteTitle); ?>
                    <img class="logo" src="<?php echo $this->assetUrl('img/logo.png'); ?>" alt="Journal of the Plague Year" />
                <?php endif; ?>
                </a>
            </h1>
            <div id="search">
                <?php echo $this->partial('common/search-form'); ?>
            </div>

            <nav>
            <?php
            echo $site->publicNav()->menu()->renderMenu(null, [
                'maxDepth' => $this->themeSetting('nav_depth') - 1
            ]);
            ?>
            </nav>
        </header>
        <div id="content" role="main">
            <?php echo $this->content; ?>
        </div>
        <footer>
            <div class="footer-partner-logo">
                <?php if ($this->themeSetting('logo')): ?>
                    <img src="<?php echo $this->themeSettingAssetUrl('logo'); ?>" alt="<?php echo $escape($siteTitle); ?>" />
                <?php endif; ?>
            </div>
            <div class="footer-asu">
                <h6>A curatorial collaborative initiated by</h6>
                <a href="https://shprs.asu.edu/" title="ASU SHPRS"><img class="asu-logo" src="<?php echo $this->assetUrl('img/asu-logo.png'); ?>" alt="Arizona State University SHPRS" /></a>
                <?php if ($this->themeSetting('tac')): ?>
                    <a class="tac" href="<?php echo $this->themeSetting('tac'); ?>"><span class="fa fa-caret-right"></span> Terms and Conditions</a>
                <?php endif; ?>
            </div>
        </footer>
    </body>
</html>
